### ISSUE TITLE
Unable to view fantayscotus_2015_build_scdb_model_40.ipynb

### ISSUE THREAD

**Issue by yas1th786** [mjbommar/scotus-predict#5]
I was trying to see the code for reference but I am unable to open it  neither unable to load the document . Please help. 
![scotus issue](https://user-images.githubusercontent.com/32835606/33370762-80bc3358-d51e-11e7-8763-77cb0d127c9e.jpg)

**Comment by aabhi1119** [comment]
Unable to open this document.

**Comment by mjbommar** [comment]
1. GitHub cannot preview some Jupyter notebooks inline.  Please download the .ipynb file and launch a local Jupyter notebook server.

2. This project should no longer be used for replicating research.  Please see v2 here: https://github.com/mjbommar/scotus-predict-v2
